### ISSUE TITLE
Fix issues on Send view

### ISSUE THREAD

**Issue by marconipoveda** [hodlwallet/hodlwallet#89]
Send view is not using the full size of the screen. this add an unnecessary scroll to the view.

**To Reproduce**

1. From Home view Click on Send ⬆
2. On Send view, scroll the Send form and the Fee entry will appear. On bigger screens the form may not move but the scroll bar shows to the side.

**Expected behavior**

No scrolling needed. The form must adjust to the size of the screen.

**Screenshots**

iOS and Android have similar behaviors.

![image](https://user-images.githubusercontent.com/47533/149246305-d8c2b7ee-7cd0-4621-8b36-48adea6d50b7.png)

![image](https://user-images.githubusercontent.com/47533/149246324-de441742-5cbc-4602-87f9-86b14a6f8f0a.png)

**Comment by igorgue** [comment]
@marconipoveda can you test it again from `main` I think I fixed that in between other things

**Comment by marconipoveda** [comment]
Thanks for the update @igorgue. You're right, it's already fixed in `main`.
